### PR TITLE
chore: Remove coveralls NPM config

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by jessebeach** [comment]
@nschonni could you rebase this and force push so that the package-lock conflicts are resolved?

I'm remembering why I don't like package-lock :)

**Comment by jessebeach** [comment]
Seems like there's a module called `request` that is now missing.

**Comment by nschonni** [comment]
Re-bumped jest to v26 like I did in #80 to resolve this

**Comment by jessebeach** [comment]
> Re-bumped jest to v26 like I did in #80 to resolve this

Shazaam! Thank you for fixing it. Sorry for the churn!

**Pull request merged**
