### PR TITLE
Remove the usage of Maps and Sets, along with the Babel Runtime dependency

### PR DESCRIPTION
**Pull request by jessebeach**
This removes and converts all usage of Maps and Sets to standard objects and arrays. The conversion wasn't one to one, so this change will be breaking (introduces a different API surface for the library) and will require a Major release.

I added a standard API to each module, that looks something like this:

```
{|
  entries: () => Array<Array<$Key, $Value>>,
  get: (key: $Key) => ?$Value,
  has: (key: $Key) => boolean,
  keys: () => Array<$Key>,
  values: () => Array<$Value>,
|}
```

### CODE REVIEW

**Comment by ljharb** [comment]
Which part is the breaking change?

**Comment by jessebeach** [comment]
> Which part is the breaking change?

The API exposed for the objects is no longer a real Map API, so the methods don't return iterables and the full set of Map methods are no longer available.

**Comment by ljharb** [comment]
They return arrays, which are iterable; but true that they’re not iterators specifically.

So it’s more like, technically a breaking change but almost certainly won’t break anyone? If so, great :-)

**Comment by jessebeach** [comment]
> They return arrays, which are iterable; but true that they’re not iterators specifically.
> 
> So it’s more like, technically a breaking change but almost certainly won’t break anyone? If so, great :-)

ya, pretty much :) I'm going to integrate with eslint-plugin-jsx-a11y and set up that PR before I land this one, just in case I need to adjust it.

**Review by eps1lon — APPROVED** [review]
We can do that as opposed to https://github.com/A11yance/aria-query/pull/180. Though the next release will be SemVer MAJOR, yes?

This PR will

Closes https://github.com/A11yance/aria-query/pull/162
Closes https://github.com/A11yance/aria-query/pull/166
Closes https://github.com/A11yance/aria-query/issues/158
https://github.com/A11yance/aria-query/pull/180

**Comment by ljharb** [comment]
It seems like the next release will be semver-major, but won't likely actually require any changes for anyone.

After this lands, #180 may indeed be unnecessary.

**Comment by jessebeach** [comment]
Changes to eslint-plugin-jsx-a11y to accommodate these changes: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/814

**Pull request merged**
