### PR TITLE
Add the scope=rowgroup attribute to the rowheader role definition

### PR DESCRIPTION
**Pull request by jessebeach**
Co-authored-by: jessebeach <splendidnoise@gmail.com>
Co-authored-by: wasanx25 <wasanx25@gmail.com>

### CODE REVIEW

**Comment by jessebeach** [comment]
Thank you for opening the issue and supplying the solution example @wasanx25.

**Comment by wasanx25** [comment]
@jessebeach Thank you for fixing my issue. I have two questions.

- Will you edit README? It seems like the list of `elementRoles` includes this case https://github.com/A11yance/aria-query#elements-to-roles
- What's next version? maybe v5.1.0?

**Comment by jessebeach** [comment]
> * Will you edit README? It seems like the list of `elementRoles` includes this case https://github.com/A11yance/aria-query#elements-to-roles

Good catch! This will be updated in #316. I'll have a new release in the next couple days. We have a newborn in the house, so whereas I have time to code, it's hard to predict when that time will be!

**Comment by wasanx25** [comment]
Thank you for editing README.
It's ok about a new release version.
Congrats on a newborn! No problem delay of a new release.

**Pull request merged**
