### PR TITLE
feat: Add graphics-* roles

### PR DESCRIPTION
**Pull request by eps1lon**
Closes https://github.com/A11yance/aria-query/issues/181

Data is based on [WAI-ARIA Graphics Module 1.0](https://www.w3.org/TR/graphics-aria-1.0/) which was parsed by https://gist.github.com/eps1lon/586e9a003c4d1cf3b74a6cd943edc46d.

### CODE REVIEW

**Comment by ljharb** [comment]
@jessebeach is there any chance that `ariaGraphicsRoles` isn't being imported into `rolesMap`, which is why my tests for https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/756#issuecomment-1292760714 are failing?

**Comment by jessebeach** [comment]
@ljharb yes, you are correct. The Graphics roles were created, but there is one missing integration point to get them surfaces: https://github.com/A11yance/aria-query/blob/main/src/rolesMap.js#L10

I can get a patch release of aria-query out later today to plug this gap.

**Comment by ljharb** [comment]
Thank you!

**Comment by jessebeach** [comment]
@ljharb try pulling in aria-query@5.1.2

**Comment by ljharb** [comment]
Unfortunately that doesn't seem to do it - was the build process not ran, perhaps?

**Comment by jessebeach** [comment]
Huh, the build is run as part of publish. I'll need to set up this PR locally and test end to end to figure out what's going on.

**Comment by jessebeach** [comment]
@ljharb what PR is failing? I don't see one in the list of PRs.

**Pull request merged**
